### ISSUE TITLE
Weapon attachment images

### ISSUE THREAD

**Issue by hugochugo** [M4RFY/qb-inventory#2]
Any clue why the images in weapon attachments looks like this?
![image](https://user-images.githubusercontent.com/66925703/233254984-923ba7fa-bb13-469f-814a-cd74fe07c429.png)

**Comment by M4RFY** [comment]
you have to put item img in the images folder

**Comment by hugochugo** [comment]
> you have to put item img in the images folder

I have done that I still have the same issue, sorry for long response didn't know you could still comment on closed issues

**Comment by M4RFY** [comment]
put the attachment images into attachment_images folder

**Comment by hugochugo** [comment]
> put the attachment images into attachment_images folder

I do I actually have them in both and I've tried just the images in each and it won't work anything else I could try?
![image](https://user-images.githubusercontent.com/66925703/235321006-d6175236-df8f-4770-9266-0fb6c0519ac2.png)

**Comment by M4RFY** [comment]
i think you should check the items.lua and match the image name because this is not a inventory issue

**Comment by hugochugo** [comment]
> i think you should check the items.lua and match the image name because this is not a inventory issue

It already is.
![image](https://user-images.githubusercontent.com/66925703/235323823-1c348096-167f-451a-946e-e5ed91832d23.png)

**Comment by M4RFY** [comment]
just check the lj and qb inventory they have the same issue some attachments image appears but not all

**Comment by hugochugo** [comment]
Ok thank you just wasn't sure if I screwed up or something
